### ISSUE TITLE
Two stages?

### ISSUE THREAD

**Issue by ToBeNormal** [nhshin-mcl/MWR#4]
Thanks for your excellent work. Is the training two-stage for global regressor and local regressor respectively?

**Comment by seon92** [comment]
Thank you for your interest on our work! 

We train a global regressor and local regressors, individually. However, training of each network does not have to be done in the sequential manner. We use those regressors sequentially during inference phase (i.e. MWR process) only.

**Comment by nhshin-mcl** [comment]
Thank you for your reply!

Let me tell you about the training and test process more specifically.

Training
- First, a global regressor is trained with the whole training dataset. Second, local regressors are trained. Each local regressor is trained with data from a specific rank range. For example, in the CLAP2015 dataset which is for facial age estimation, we use five local regressors, and those trained with data from [3, 18], [10, 29], [19, 44], [30, 62],  and [45, 85], respectively.

Test
- First, we do the initial prediction. Second, we perform MWR using the global regressor to obtain the global estimate. Third, starting from the global estimate, we iteratively refine the estimate using local regressors.  At each iteration, due to the overlap, the previous estimate may belong to two rank groups. In such a case, both groups are selected and the estimated ranks from the corresponding local regressors are averaged.

Please find more details in our paper.

Thank you

**Comment by ToBeNormal** [comment]
@nhshin-mcl Thanks for your nice reply! Have a good day!

**Comment by Doanhdz** [comment]
@ZhouCX117 Can you help me some idea about the training code ?
